In [7]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import pandas_datareader as pdr
from datetime import datetime
import statistics 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pylab
bp = pdr.get_data_yahoo(symbols='TLT', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for TLT=',statistics.stdev(re))
print('average return for TLT=',np.average(re))

sd_tlt = statistics.stdev(re)
ar_tlt = np.average(re)


#sre = [(df.iloc[j]['Return'] - ar) / sd for j in range(0,len(Date))]

#sre2 = pd.DataFrame({'Date':Date, 'Standard Return':sre})


bp = pdr.get_data_yahoo(symbols='BTCUSD=X', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for BTC=',statistics.stdev(re))
print('average return for BTC=',np.average(re))

sd_BTC = statistics.stdev(re)
ar_BTC = np.average(re)


bp = pdr.get_data_yahoo(symbols='VXX', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for VXX=',statistics.stdev(re))
print('average return for VXX=',np.average(re))

sd_VXX = statistics.stdev(re)
ar_VXX = np.average(re)

bp = pdr.get_data_yahoo(symbols='XLF', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for XLF=',statistics.stdev(re))
print('average return for XLF=',np.average(re))

sd_XLF = statistics.stdev(re)
ar_XLF = np.average(re)

bp = pdr.get_data_yahoo(symbols='FXI', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for FXI=',statistics.stdev(re))
print('average return for FXI=',np.average(re))

sd_FXI = statistics.stdev(re)
ar_FXI = np.average(re)




standard deviation for TLT= 0.00792344262080027
average return for TLT= -4.975134139243566e-05
standard deviation for BTC= 0.044219666899159696
average return for BTC= -0.0037343706417478084


RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/VXX?period1=1425139200&period2=1519919999&interval=1d&events=history&crumb=CiJ%5Cu002FzQavNZm

In [63]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import pandas_datareader as pdr
from datetime import datetime
import statistics 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pylab
from tradingWithPython import yahooFinance as yf
df = yf.getSymbolData("SPY")
#df.head()

dfspy = yf.getSymbolData("SPY",adjust=True)
dfspy.head()
dfspy = dfspy.rename(columns={'close':'SPY close'})

dfvxx = yf.getSymbolData("VXX",adjust=True)
dfvxx.head()
dfvxx = dfvxx.rename(columns={'close':'VXX close'})

dfxlf = yf.getSymbolData("XLF", adjust=True)
dfxlf.head()
dfxlf = dfxlf.rename(columns={'close':'XLF close'})

dffxi = yf.getSymbolData("fXI", adjust=True)
dffxi.head()
dffxi = dffxi.rename(columns={'close':'FXI close'})

dfbtc = pdr.get_data_yahoo(symbols='BTCUSD=X', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))
dfbtc.head()
dfbtc = dfbtc.rename(columns={'Close':'BTC close'})
Date = dfbtc.index
#print(dffxi)


#dfspy.drop('volume','open','high','low', inplace=True)
#dfvxx.drop('volume','open','high','low', inplace=True)
#dfxlf.drop('volume','open','high','low', inplace=True)
#dffxi.drop('volume','open','high','low', inplace=True)
#dfbtc.drop('volume','open','high','low', inplace=True)

#dfspy.drop(dfspy.columns[[2,3,4,]], axis=1, inplace=True)
#dfvxx.drop(dfvxx.columns[[2,3,4]], axis=1, inplace=True)
#dfxlf.drop(dfxlf.columns[[2,3,4]], axis=1, inplace=True)
#dffxi.drop(dffxi.columns[[2,3,4]], axis=1, inplace=True)
#dfbtc.drop(dfbtc.columns[[2,3,4]], axis=1, inplace=True)

del dfspy['volume','open','high','low']
del dfvxx['volume','open','high','low']
del dfxlf['volume','open','high','low']
del dffxi['volume','open','high','low']
del dfbtc['Volume','Open','High','Low','Adj Close']

dfmix = pd.concat([dfspy,dfvxx,dfxlf,dffxi,dfbtc])
#pd.concat([dfspy,dfvxx,dfxlf,dffxi,bp],index='Date')

ConnectionError: HTTPSConnectionPool(host='query1.finance.yahoo.com', port=443): Max retries exceeded with url: /v7/finance/download/SPY?period1=946656000&period2=1521090160&interval=1d&events=history&crumb=13FfXJ5m1MY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11361bbe0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

In [80]:
print(dfbtc.columns.tolist())
dfmix = pd.DataFrame({'SPY close': dfspy['SPY close'],'VXX close': dfvxx['VXX close'], 'XLF close' : dfxlf['XLF close'], 'FXI close': dffxi['FXI close'], 'BTC close': dfbtc['BTC close']},index=dfbtc.index)
dfmix.head()
dfmix.dropna()

['Open', 'High', 'Low', 'BTC close', 'Adj Close', 'Volume']


BTC close  FXI close   SPY close   VXX close  XLF close
Date                                                               
2015-03-02   0.003653  41.364376  199.459213  427.200012  14.500768
2015-03-03   0.003563  40.279568  198.640625  436.480011  14.459386
2015-03-04   0.003678  39.638111  197.803238  435.519989  14.370716
2015-03-05   0.003633  39.336254  198.019653  430.079987  14.429828
2015-03-06   0.003669  38.921188  195.234604  448.480011  14.323425
2015-03-09   0.003448  39.373985  196.043793  442.559998  14.388450
2015-03-10   0.003432  38.458961  192.863571  456.160004  14.081054
2015-03-11   0.003383  38.553299  192.411972  467.679993  14.169726
2015-03-12   0.003403  38.940056  194.858276  439.679993  14.477120
2015-03-13   0.003482  39.138153  193.663330  449.600006  14.376628
2015-03-16   0.003443  39.845642  196.250778  438.559998  14.553970
2015-03-17   0.003504  40.015434  195.667419  436.799988  14.518500
2015-03-18   0.003907  40.713493  198.019653  418.079987  14.601260
2015-03-19   0.003832  40.704060  197.116409  418.079987  14.465296
2015-03-20   0.003820  40.883286  198.856308  411.679993  14.661694
2015-03-23   0.003767  40.751221  198.468826  403.839996  14.578627
2015-03-24   0.004053  40.562561  197.353638  402.399994  14.459954
2015-03-25   0.004059  40.100334  194.461639  420.320007  14.228550
2015-03-26   0.004032  40.062607  193.998535  416.799988  14.216682
2015-03-27   0.004045  40.656891  194.442749  411.839996  14.198882
2015-03-30   0.004096  42.203930  196.814926  399.359985  14.406555
2015-03-31   0.004061  41.883202  195.094849  410.079987  14.305686
2015-04-01   0.003959  42.637852  194.404922  408.320007  14.293818
2015-04-02   0.003930  43.071777  195.104324  400.959991  14.365020
2015-04-06   0.003953  43.600037  196.418015  392.480011  14.388752
2015-04-07   0.004089  43.741531  195.898178  391.200012  14.311617
2015-04-08   0.004110  46.429985  196.559738  383.519989  14.365020
2015-04-09   0.004260  48.222282  197.429214  370.239990  14.388752
2015-04-13   0.004587  48.429810  197.608795  362.559998  14.436221
2015-04-14   0.004485  48.099651  197.986877  359.519989  14.436221
...               ...        ...         ...         ...        ...
2018-01-18   0.000089  51.070000  279.140015   26.959999  29.330000
2018-01-19   0.000087  51.919998  280.410004   26.820000  29.540001
2018-01-22   0.000092  52.209999  282.690002   26.250000  29.780001
2018-01-23   0.000092  53.029999  283.290009   26.690001  29.809999
2018-01-24   0.000087  53.349998  283.179993   27.370001  30.010000
2018-01-25   0.000089  52.639999  283.299988   27.820000  29.950001
2018-01-26   0.000090  54.000000  286.579987   27.639999  30.170000
2018-01-29   0.000089  52.849998  284.679993   29.650000  30.049999
2018-01-30   0.000099  51.980000  281.760010   30.600000  29.660000
2018-01-31   0.000098  52.669998  281.899994   29.959999  29.740000
2018-02-01   0.000110  51.910000  281.579987   29.010000  30.020000
2018-02-02   0.000113  51.070000  275.450012   32.919998  29.360001
2018-02-05   0.000144  49.880001  263.929993   43.939999  27.879999
2018-02-06   0.000130  50.770000  269.130005   42.880001  28.389999
2018-02-07   0.000132  48.060001  267.670013   44.570000  28.410000
2018-02-08   0.000121  46.049999  257.630005   55.240002  27.160000
2018-02-09   0.000115  46.119999  261.500000   50.029999  27.680000
2018-02-12   0.000112  46.689999  265.339996   47.950001  28.070000
2018-02-13   0.000117  46.689999  266.000000   47.980000  28.190001
2018-02-14   0.000105  48.110001  269.589996   42.340000  28.860001
2018-02-15   0.000100  49.360001  273.029999   41.540001  29.020000
2018-02-16   0.000098  49.369999  273.109985   42.150002  28.980000
2018-02-20   0.000089  48.369999  271.399994   43.900002  28.889999
2018-02-21   0.000095  49.080002  270.049988   44.360001  28.930000
2018-02-22   0.000102  48.779999  270.399994   43.820000  28.690001
2018-02-23   0.000098  49.700001  274.709991   40.410000  29.120001


In [169]:
re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['BTC close']
    p2 = dfmix.iloc[i]['BTC close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfb = pd.DataFrame({'Date':Date,'BTC Return':re})


re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['FXI close']
    p2 = dfmix.iloc[i]['FXI close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dff = pd.DataFrame({'Date':Date,'FXI Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['SPY close']
    p2 = dfmix.iloc[i]['SPY close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfs = pd.DataFrame({'Date':Date,'SPY Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['VXX close']
    p2 = dfmix.iloc[i]['VXX close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfv = pd.DataFrame({'Date':Date,'VXX Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['XLF close']
    p2 = dfmix.iloc[i]['XLF close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfx = pd.DataFrame({'Date':Date,'XLF Return':re})

#df_return=pd.concat([dfb,dff,dfs,dfv,dfx])

df_return = pd.DataFrame({'SPY Return': dfs['SPY Return'],'VXX Return': dfv['VXX Return'], 'XLF Return' : dfx['XLF Return'], 'FXI Return': dff['FXI Return'], 'BTC Return': dfb['BTC Return']},index=dfb.index)
df_return.head()
#calculate daily returns
#df_std = pd.DataFrame({'std':[np.std(dfs['SPY Return']),np.std(dfs['VXX Return']),np.std(dfs['XLF Return']),np.std(dfs['FXI Return']),np.std(dfs['BTC Return'])]})

print(np.std(df_return['FXI Return']))
std=[]
std = [np.std(df_return['BTC Return']),np.std(df_return['FXI Return']),np.std(dfs['SPY Return']),np.std(df_return['VXX Return']),np.std(df_return['XLF Return'])]
#calculate standard deviation for 5 assets
print(std)
print(type(std))

df_std = pd.DataFrame({'std': std})

pd.concat([df_std.T[x] for x in df_std.T], ignore_index=True)

#df_std = pd.concat([df_std.T[x] for x in df_std.T], index=df_return.index)

df_std.set_index = df_return.index
print(df_std)


0.014629048879833953
[0.035989340217346094, 0.014629048879833953, 0.0079758047547375, 0.037561451371426045, 0.010891053169196615]
<class 'list'>
        std
0  0.035989
1  0.014629
2  0.007976
3  0.037561
4  0.010891


In [109]:
#b=[]
#for i in range(0, len(Date)-1):
#    b.append((dfmix.iloc[i+1]['BTC close'] - dfmix.iloc[i]['BTC close']) / dfmix.iloc[i]['BTC close'])
#dfmix['BTC Standard'] = b
#dfb = pd.DataFrame({'Date':Date,'Return':b})

ValueError: Length of values does not match length of index

In [137]:
df_return['BTC Return'].corr(df_return['FXI Return'])
df_return_corr=df_return.corr()
print(df_return.corr())
Covariance = np.cov(df_return_corr,bias=True)
#my_columns  = ["BTC cov","FXI cov","SPY cov","VXX cov","XLF cov"]
#my_columns2 = ['BTC cov','FXI cov','SPY cov','VXX cov','XLF cov']
#Covariance.columns = my_columns
#Covariance.index = ['BTC', "FXI","SPY","VXX","XLF"]
print('Covariance=')
print(Covariance)

            BTC Return  FXI Return  SPY Return  VXX Return  XLF Return
BTC Return    1.000000    0.032334    0.011563   -0.064262    0.024687
FXI Return    0.032334    1.000000    0.646663   -0.561289    0.520835
SPY Return    0.011563    0.646663    1.000000   -0.827555    0.835022
VXX Return   -0.064262   -0.561289   -0.827555    1.000000   -0.678740
XLF Return    0.024687    0.520835    0.835022   -0.678740    1.000000
Covariance=
[[ 0.16083724 -0.04161046 -0.04334964  0.01086982 -0.04446894]
 [-0.04161046  0.29371359  0.32944871 -0.32848007  0.28114392]
 [-0.04334964  0.32944871  0.44910172 -0.44170376  0.40037843]
 [ 0.01086982 -0.32848007 -0.44170376  0.44169903 -0.39143923]
 [-0.04446894  0.28114392  0.40037843 -0.39143923  0.37012026]]


In [170]:
eig_vals, eig_vecs = np.linalg.eig(df_return_corr)
eig_vec_list = [ eig_vecs[i] for i in range(len(eig_vals))]
index_corr = df_return_corr.index
df_eig = pd.DataFrame({'Eigenvalue': eig_vals, 'Eigenvector': eig_vec_list}, index = index_corr)
res = pd.concat([df_std, df_eig], axis=1)
#df_stock = res.dropna()
print(df_eig)

            Eigenvalue                                        Eigenvector
BTC Return    3.053150  [-0.03187244607035623, -0.998080660127957, -0....
FXI Return    1.000040  [-0.43834886637146103, 0.0076292178604933855, ...
SPY Return    0.107875  [-0.5464348650886341, 0.04529357611045659, -0....
VXX Return    0.316860  [0.5068270944175985, 0.02527357607537022, -0.3...
XLF Return    0.522075  [-0.5013677822837521, 0.03296254281555635, 0.4...


In [171]:
weight = np.zeros(5,)
for i in range(5):
    weight[i] = df_eig['Eigenvector'][i][0] / df_std['std'][i] / (df_eig['Eigenvalue'][0]**0.5)
    
df_weight = pd.DataFrame({'Weight':weight}, index = df_eig.index)
print(df_weight)

               Weight
BTC Return  -0.506836
FXI Return -17.148642
SPY Return -39.209367
VXX Return   7.722242
XLF Return -26.345867


In [172]:
df_weight['Weight'][0]

-0.5068360005321995

In [177]:
Covariance[0]

array([ 0.16083724, -0.04161046, -0.04334964,  0.01086982, -0.04446894])

In [178]:
Covariance[0][0]

0.16083724013822198

In [180]:
re = []
for i in range(5):
    for j in range(5):
        p123 = df_weight['Weight'][i] * Covariance[i][j] * df_weight['Weight'][j]
        re.append(p123)
print(re)

[0.041316309563249984, -0.36165932631413844, -0.861475248011884, -0.04254349117645603, -0.5937952204088596, -0.36165932631413844, 86.37409919245923, 221.51716419409408, 43.49929028953225, 127.0196565033524, -0.861475248011884, 221.5171641940941, 690.4375128954476, 133.74092964585992, 413.59282038271084, -0.04254349117645604, 43.49929028953225, 133.74092964585995, 26.33984711702032, 79.63798114035613, -0.5937952204088597, 127.0196565033524, 413.5928203827108, 79.63798114035613, 256.9022065987549]


In [183]:
segma = sum(re)
print(segma)

3094.3917198532336


In [187]:
sharp_ratio = (1.5 - 1.0) /segma
print(sharp_ratio)

0.00016158264540072997


Thus, the portfolio's value will be 1.5+1*sharp_ratio= 1.5001615