In [8]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import pandas_datareader as pdr
from datetime import datetime
import statistics 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pylab
bp = pdr.get_data_yahoo(symbols='TLT', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for TLT=',statistics.stdev(re))
print('average return for TLT=',np.average(re))

sd_tlt = statistics.stdev(re)
ar_tlt = np.average(re)


#sre = [(df.iloc[j]['Return'] - ar) / sd for j in range(0,len(Date))]

#sre2 = pd.DataFrame({'Date':Date, 'Standard Return':sre})


bp = pdr.get_data_yahoo(symbols='BTCUSD=X', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for BTC=',statistics.stdev(re))
print('average return for BTC=',np.average(re))

sd_BTC = statistics.stdev(re)
ar_BTC = np.average(re)


bp = pdr.get_data_yahoo(symbols='VXX', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for VXX=',statistics.stdev(re))
print('average return for VXX=',np.average(re))

sd_VXX = statistics.stdev(re)
ar_VXX = np.average(re)

bp = pdr.get_data_yahoo(symbols='XLF', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for XLF=',statistics.stdev(re))
print('average return for XLF=',np.average(re))

sd_XLF = statistics.stdev(re)
ar_XLF = np.average(re)

bp = pdr.get_data_yahoo(symbols='FXI', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))


Date = bp.index
#print(bp)m

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = bp.iloc[i-1]['Close']
    p2 = bp.iloc[i]['Close']
    re.append((p2-p1)/p1)
Date = Date[1:]
df = pd.DataFrame({'Date':Date,'Return':re})

#print(df)
#print(type(df))
print('standard deviation for FXI=',statistics.stdev(re))
print('average return for FXI=',np.average(re))

sd_FXI = statistics.stdev(re)
ar_FXI = np.average(re)




standard deviation for TLT= 0.00792344262080027
average return for TLT= -4.975134139243566e-05
standard deviation for BTC= 4334035.313712648
average return for BTC= 154786.9717553668
standard deviation for VXX= 0.04273374171107455
average return for VXX= -0.002032156173518069
standard deviation for XLF= 0.010779755988655043
average return for XLF= 0.000525552863254229
standard deviation for FXI= 0.015165398760932704
average return for FXI= 0.00021416600887692966


In [9]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import pandas_datareader as pdr
from datetime import datetime
import statistics 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats
import pylab
from tradingWithPython import yahooFinance as yf
df = yf.getSymbolData("SPY")
#df.head()

dfspy = yf.getSymbolData("SPY",adjust=True)
dfspy.head()
dfspy = dfspy.rename(columns={'close':'SPY close'})

dfvxx = yf.getSymbolData("VXX",adjust=True)
dfvxx.head()
dfvxx = dfvxx.rename(columns={'close':'VXX close'})

dfxlf = yf.getSymbolData("XLF", adjust=True)
dfxlf.head()
dfxlf = dfxlf.rename(columns={'close':'XLF close'})

dffxi = yf.getSymbolData("fXI", adjust=True)
dffxi.head()
dffxi = dffxi.rename(columns={'close':'FXI close'})

dfbtc = pdr.get_data_yahoo(symbols='BTCUSD=X', start=datetime(2015, 3, 1), end=datetime(2018, 3, 1))
dfbtc.head()
dfbtc = dfbtc.rename(columns={'Close':'BTC close'})
Date = dfbtc.index
#print(dffxi)


#dfspy.drop('volume','open','high','low', inplace=True)
#dfvxx.drop('volume','open','high','low', inplace=True)
#dfxlf.drop('volume','open','high','low', inplace=True)
#dffxi.drop('volume','open','high','low', inplace=True)
#dfbtc.drop('volume','open','high','low', inplace=True)

#dfspy.drop(dfspy.columns[[2,3,4,]], axis=1, inplace=True)
#dfvxx.drop(dfvxx.columns[[2,3,4]], axis=1, inplace=True)
#dfxlf.drop(dfxlf.columns[[2,3,4]], axis=1, inplace=True)
#dffxi.drop(dffxi.columns[[2,3,4]], axis=1, inplace=True)
#dfbtc.drop(dfbtc.columns[[2,3,4]], axis=1, inplace=True)

del dfspy['volume','open','high','low']
del dfvxx['volume','open','high','low']
del dfxlf['volume','open','high','low']
del dffxi['volume','open','high','low']
del dfbtc['Volume','Open','High','Low','Adj Close']

dfmix = pd.concat([dfspy,dfvxx,dfxlf,dffxi,dfbtc])
#pd.concat([dfspy,dfvxx,dfxlf,dffxi,bp],index='Date')

/Users/zhousq/anaconda3/lib/python3.6/site-packages/tradingWithPython/lib/cboe.py:11: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


Got 4585 days of data
Got 4585 days of data
Got 2303 days of data
Got 4585 days of data
Got 3388 days of data


KeyError: ('volume', 'open', 'high', 'low')

In [10]:
print(dfbtc.columns.tolist())
dfmix = pd.DataFrame({'SPY close': dfspy['SPY close'],'VXX close': dfvxx['VXX close'], 'XLF close' : dfxlf['XLF close'], 'FXI close': dffxi['FXI close'], 'BTC close': dfbtc['BTC close']},index=dfbtc.index)
dfmix.head()
dfmix.dropna()

['Open', 'High', 'Low', 'BTC close', 'Adj Close', 'Volume']


BTC close  FXI close   SPY close   VXX close  XLF close
Date                                                                  
2015-03-02      0.003653  41.364376  198.663910  427.200012  14.448174
2015-03-03      0.003563  40.279568  197.848602  436.480011  14.406942
2015-03-04      0.003678  39.638111  197.014557  435.519989  14.318594
2015-03-05      0.003633  39.336254  197.230118  430.079987  14.377492
2015-03-06      0.003669  38.921188  194.456146  448.480011  14.271475
2015-03-09      0.003448  39.373985  195.262115  442.559998  14.336264
2015-03-10      0.003432  38.458961  192.094604  456.160004  14.029983
2015-03-11      0.003383  38.553299  191.644791  467.679993  14.118334
2015-03-12      0.003403  38.940056  194.081314  439.679993  14.424613
2015-03-13      0.003482  39.138153  192.891144  449.600006  14.324485
2015-03-16      0.003443  39.845642  195.468277  438.559998  14.501184
2015-03-17      0.003504  40.015434  194.887268  436.799988  14.465842
2015-03-18      0.003907  40.713493  197.230118  418.079987  14.548303
2015-03-19      0.003832  40.704060  196.330444  418.079987  14.412831
2015-03-20      0.003820  40.883286  198.063431  411.679993  14.608517
2015-03-23      0.003767  40.751221  197.677490  403.839996  14.525751
2015-03-24      0.004053  40.562561  196.566742  402.399994  14.407509
2015-03-25      0.004059  40.100334  193.686279  420.320007  14.176944
2015-03-26      0.004032  40.062607  193.225021  416.799988  14.165119
2015-03-27      0.004045  40.656891  193.667465  411.839996  14.147384
2015-03-30      0.004096  42.203930  196.030182  399.359985  14.354303
2015-03-31      0.004061  41.883202  194.316956  410.079987  14.253800
2015-04-01      0.003959  42.637852  193.629807  408.320007  14.241975
2015-04-02      0.003930  43.071777  194.326416  400.959991  14.312919
2015-04-06      0.003953  43.600037  195.634827  392.480011  14.336565
2015-04-07      0.004089  43.741531  195.117081  391.200012  14.259709
2015-04-08      0.004110  46.429985  195.776016  383.519989  14.312919
2015-04-09      0.004260  48.222282  196.642014  370.239990  14.336565
2015-04-13      0.004587  48.429810  196.820877  362.559998  14.383862
2015-04-14      0.004485  48.099651  197.197418  359.519989  14.383862
...                  ...        ...         ...         ...        ...
2018-01-19      0.000087  51.919998  279.291412   26.820000  29.432861
2018-01-22      0.000092  52.209999  281.562317   26.250000  29.671989
2018-01-23      0.000092  53.029999  282.159943   26.690001  29.701880
2018-01-24      0.000087  53.349998  282.050354   27.370001  29.901155
2018-01-25      0.000089  52.639999  282.169861   27.820000  29.841373
2018-01-26      0.000090  54.000000  285.436798   27.639999  30.060575
2018-01-29      0.000089  52.849998  283.544373   29.650000  29.941010
2018-01-30      0.000099  51.980000  280.636047   30.600000  29.552425
2018-01-31      0.000098  52.669998  280.775452   29.959999  29.632135
2018-02-01      0.000110  51.910000  280.456726   29.010000  29.911119
2018-02-02      0.000113  51.070000  274.351227   32.919998  29.253513
2018-02-05      0.000144  49.880001  262.877136   43.939999  27.778879
2018-02-06      0.000130  50.770000  268.056427   42.880001  28.287031
2018-02-07      0.000132  48.060001  266.602264   44.570000  28.306959
2018-02-08      0.000121  46.049999  256.602295   55.240002  27.061493
2018-02-09      0.000115  46.119999  260.456848   50.029999  27.579607
2018-02-12      0.000112  46.689999  264.281525   47.950001  27.968191
2018-02-13      0.000117  46.689999  264.938904   47.980000  28.087757
2018-02-14      0.000105  48.110001  268.514587   42.340000  28.755327
2018-02-15      0.000100  49.360001  271.940857   41.540001  28.914747
2018-02-16      0.000098  49.369999  272.020508   42.150002  28.874891
2018-02-20      0.000089  48.369999  270.317352   43.900002  28.785217
2018-02-21      0.000095  49.080002  268.972717   44.360001  28.825073
2018-02-22      0.000102  48.779999  26

In [12]:
re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['BTC close']
    p2 = dfmix.iloc[i]['BTC close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfb = pd.DataFrame({'Date':Date,'BTC Return':re})


re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['FXI close']
    p2 = dfmix.iloc[i]['FXI close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dff = pd.DataFrame({'Date':Date,'FXI Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['SPY close']
    p2 = dfmix.iloc[i]['SPY close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfs = pd.DataFrame({'Date':Date,'SPY Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['VXX close']
    p2 = dfmix.iloc[i]['VXX close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfv = pd.DataFrame({'Date':Date,'VXX Return':re})

re = []
f = 1
mu = 0
for i in range(1, len(Date)):
    #day1 = Date[i].date()
    #day1 = Date[i-1].date()
    p1 = dfmix.iloc[i-1]['XLF close']
    p2 = dfmix.iloc[i]['XLF close']
    re.append((p2-p1)/p1)
Date = Date[1:]
dfx = pd.DataFrame({'Date':Date,'XLF Return':re})

#df_return=pd.concat([dfb,dff,dfs,dfv,dfx])

df_return = pd.DataFrame({'SPY Return': dfs['SPY Return'],'VXX Return': dfv['VXX Return'], 'XLF Return' : dfx['XLF Return'], 'FXI Return': dff['FXI Return'], 'BTC Return': dfb['BTC Return']},index=dfb.index)
df_return.head()
#calculate daily returns
#df_std = pd.DataFrame({'std':[np.std(dfs['SPY Return']),np.std(dfs['VXX Return']),np.std(dfs['XLF Return']),np.std(dfs['FXI Return']),np.std(dfs['BTC Return'])]})

print(np.std(df_return['FXI Return']))
std=[]
std = [np.std(df_return['BTC Return']),np.std(df_return['FXI Return']),np.std(dfs['SPY Return']),np.std(df_return['VXX Return']),np.std(df_return['XLF Return'])]
#calculate standard deviation for 5 assets
print(std)
print(type(std))

df_std = pd.DataFrame({'std': std})

pd.concat([df_std.T[x] for x in df_std.T], ignore_index=True)

#df_std = pd.concat([df_std.T[x] for x in df_std.T], index=df_return.index)

df_std.set_index = df_return.index
print(df_std)


0.014340230369008018
[0.04422593395315757, 0.014340230369008018, 0.007957921291650275, 0.040968671139671516, 0.010762667920272225]
<class 'list'>
        std
0  0.044226
1  0.014340
2  0.007958
3  0.040969
4  0.010763


In [13]:
#b=[]
#for i in range(0, len(Date)-1):
#    b.append((dfmix.iloc[i+1]['BTC close'] - dfmix.iloc[i]['BTC close']) / dfmix.iloc[i]['BTC close'])
#dfmix['BTC Standard'] = b
#dfb = pd.DataFrame({'Date':Date,'Return':b})

In [14]:
df_return['BTC Return'].corr(df_return['FXI Return'])
df_return_corr=df_return.corr()
print(df_return.corr())
Covariance = np.cov(df_return_corr,bias=True)
#my_columns  = ["BTC cov","FXI cov","SPY cov","VXX cov","XLF cov"]
#my_columns2 = ['BTC cov','FXI cov','SPY cov','VXX cov','XLF cov']
#Covariance.columns = my_columns
#Covariance.index = ['BTC', "FXI","SPY","VXX","XLF"]
print('Covariance=')
print(Covariance)

            BTC Return  FXI Return  SPY Return  VXX Return  XLF Return
BTC Return    1.000000   -0.012388   -0.072973    0.051419   -0.052453
FXI Return   -0.012388    1.000000    0.651592   -0.555430    0.531497
SPY Return   -0.072973    0.651592    1.000000   -0.838357    0.849651
VXX Return    0.051419   -0.555430   -0.838357    1.000000   -0.710542
XLF Return   -0.052453    0.531497    0.849651   -0.710542    1.000000
Covariance=
[[ 0.16878781 -0.08478155 -0.10644073  0.08011119 -0.10113954]
 [-0.08478155  0.29877949  0.34153918 -0.33905362  0.29783503]
 [-0.10644073  0.34153918  0.46981652 -0.46225727  0.42611859]
 [ 0.08011119 -0.33905362 -0.46225727  0.45942712 -0.41810965]
 [-0.10113954  0.29783503  0.42611859 -0.41810965  0.39766677]]


In [15]:
eig_vals, eig_vecs = np.linalg.eig(df_return_corr)
eig_vec_list = [ eig_vecs[i] for i in range(len(eig_vals))]
index_corr = df_return_corr.index
df_eig = pd.DataFrame({'Eigenvalue': eig_vals, 'Eigenvector': eig_vec_list}, index = index_corr)
res = pd.concat([df_std, df_eig], axis=1)
#df_stock = res.dropna()
print(df_eig)

            Eigenvalue                                        Eigenvector
BTC Return    3.090378  [-0.046761068909685656, 0.9965455115402527, -0...
FXI Return    0.997839  [0.4334913555139699, 0.08132206747689241, 0.88...
SPY Return    0.521927  [0.5454691676158124, -0.0009257517092570362, -...
VXX Return    0.101127  [-0.5068863990794862, -0.013813069992210457, 0...
XLF Return    0.288729  [0.5053990628580838, 0.00959723144571824, -0.3...


In [16]:
weight = np.zeros(5,)
for i in range(5):
    weight[i] = df_eig['Eigenvector'][i][0] / df_std['std'][i] / (df_eig['Eigenvalue'][0]**0.5)
    
df_weight = pd.DataFrame({'Weight':weight}, index = df_eig.index)
print(df_weight)

               Weight
BTC Return  -0.601453
FXI Return  17.195648
SPY Return  38.991038
VXX Return  -7.038060
XLF Return  26.712142


In [17]:
df_weight['Weight'][0]

-0.6014529312989353

In [18]:
Covariance[0]

array([ 0.16878781, -0.08478155, -0.10644073,  0.08011119, -0.10113954])

In [30]:
Covariance[0][0]

0.16878780926212436

In [20]:
re = []
for i in range(5):
    for j in range(5):
        p123 = df_weight['Weight'][i] * Covariance[i][j] * df_weight['Weight'][j]
        re.append(p123)
print(re)
#re is segma square

[0.06105825215615667, 0.8768423742497274, 2.4961707108501687, 0.339115634268441, 1.6249176287756781, 0.8768423742497273, 88.34619816603816, 228.99387704476476, 41.0336276547152, 136.80533830961028, 2.4961707108501687, 228.99387704476476, 714.2625432090688, 126.85323204019792, 443.8170714244685, 0.339115634268441, 41.0336276547152, 126.85323204019794, 22.75739828364706, 78.60531302193911, 1.6249176287756781, 136.80533830961025, 443.8170714244685, 78.6053130219391, 283.75057190129485]


In [21]:
segma = sum(re)
print(segma)

3232.0687814998846


In [22]:
sharp_ratio = (1.5 - 1.0) /segma
print(sharp_ratio)

0.00015469967807057878


Thus, the portfolio's value will be 1.5+1*sharp_ratio= 1.5001615

In [25]:
print(Covariance)

[[ 0.16878781 -0.08478155 -0.10644073  0.08011119 -0.10113954]
 [-0.08478155  0.29877949  0.34153918 -0.33905362  0.29783503]
 [-0.10644073  0.34153918  0.46981652 -0.46225727  0.42611859]
 [ 0.08011119 -0.33905362 -0.46225727  0.45942712 -0.41810965]
 [-0.10113954  0.29783503  0.42611859 -0.41810965  0.39766677]]


In [26]:
print(df_std)

        std
0  0.044226
1  0.014340
2  0.007958
3  0.040969
4  0.010763


In [35]:
Cov_min = 1/Covariance
pmin = []
for i in range(5):
    for j in range(5):
        pmin = sum(Covariance[i])/sum(Covariance[i][j])
        minimum_variance.append(pmin)
print(minimum_variacne)

TypeError: 'numpy.float64' object is not iterable

In [39]:
print(Cov_min)
Cov_min.sum(axis=0)

[[  5.92459849 -11.79501937  -9.39489995  12.48265084  -9.8873297 ]
 [-11.79501937   3.34694996   2.92792177  -2.94938603   3.35756337]
 [ -9.39489995   2.92792177   2.12849051  -2.1632975    2.34676452]
 [ 12.48265084  -2.94938603  -2.1632975    2.17662378  -2.3917171 ]
 [ -9.8873297    3.35756337   2.34676452  -2.3917171    2.51466823]]


array([-12.66999968,  -5.1119703 ,  -4.15502066,   7.15487399,
        -4.06005067])

In [58]:
#minimum-variance model
#print(Cov_min)
#Cov_min.sum(axis=0)
Cov_min_sum = np.sum(Cov_min,axis = 1)
theta_min_variance = Cov_min_sum / Cov_min.sum()
print('Minimum Variance Model',theta_min_variance)

#print(Cov_min.sum(axis=0))
#print(Cov_min.sum(axis= 1))
#Cov_min.sum()

Minimum Variance Model [ 0.67242794  0.27130479  0.22051713 -0.3797267   0.21547684]


In [84]:
#risk_parity_model
segma_risk_parity = []
for i in range(25):
    p_risk_parity = 1 / re[i]**0.5 #because re is segma square, we only need segma here
    segma_risk_parity.append(p_risk_parity)
#print(segma_risk_parity)

#sum each row 
v = []
v1= 0
for i in range(5):
    v1 = v1 + segma_risk_parity[i]
v.append(v1)


v1 = 0
for i in range(5,10):
    v1 = v1 + segma_risk_parity[i]
v.append(v1)

v1= 0
for i in range(10,15):
    v1 = v1 + segma_risk_parity[i]
v.append(v1)

v1= 0
for i in range(15,20):
    v1 = v1 + segma_risk_parity[i]
v.append(v1)

v1= 0
for i in range(20,25):
    v1 = v1 + segma_risk_parity[i]
v.append(v1)

#print(v)

theta_risk_parity = []
for i in range(5):
    v1 = 1 / re[i]**0.5 / v[i]
    theta_risk_parity.append(v1)
print('risk parity model',theta_risk_parity)

risk parity model [0.49056811523819827, 0.7205938778810643, 0.7252710699019662, 0.7516731108638546, 0.7199715954236512]


In [92]:
df_return_corr
eigenvals, eigenvec = np.linalg.eig(df_return_corr)
print(eigenvals)
print(eigenvec)

[3.09037757 0.99783898 0.52192727 0.10112726 0.28872893]
[[-4.67610689e-02  9.96545512e-01 -6.55718858e-02 -2.02557129e-02
  -6.92637586e-04]
 [ 4.33491356e-01  8.13220675e-02  8.86394247e-01  1.28802008e-01
   5.64557203e-02]
 [ 5.45469168e-01 -9.25751709e-04 -1.48716895e-01 -8.24333509e-01
   2.86370703e-02]
 [-5.06886399e-01 -1.38130700e-02  2.53451290e-01 -3.55300995e-01
   7.43235510e-01]
 [ 5.05399063e-01  9.59723145e-03 -3.51640862e-01  4.20993133e-01
   6.66027902e-01]]


In [96]:
segma1 = []
for i in range(25):
    v2 = re[i] ** 0.5
    segma1.append(v2)
#print(segma1)

[0.2470996806071523, 0.9363986193121642, 1.5799274384762638, 0.5823363583603903, 1.2747225693364332, 0.9363986193121642, 9.399265831225232, 15.13254364093376, 6.4057495778960325, 11.69638141946518, 1.5799274384762638, 15.13254364093376, 26.725690696576372, 11.262914011933054, 21.066966355516602, 0.5823363583603903, 6.4057495778960325, 11.262914011933054, 4.770471494899331, 8.865963739038138, 1.2747225693364332, 11.696381419465178, 21.066966355516602, 8.865963739038136, 16.844897503436904]


In [104]:
eigenvec[0][0]
np.sum(eigenvec, axis = 0)

bottom = []
v2 = 0
for i in range(5):
    v2 = v2 + eigenvec[0][i] / segma1[i]
bottom.append(v2)

v2 = 0
for i in range(5,10):
    v2 = v2 + eigenvec[0][i-5] / segma1[i]
bottom.append(v2)

v2 = 0
for i in range(10,15):
    v2 = v2 + eigenvec[0][i-10] / segma1[i]
bottom.append(v2)

v2 = 0
for i in range(15,20):
    v2 = v2 + eigenvec[0][i-15] / segma1[i]
bottom.append(v2)

v2 = 0
for i in range(20,25):
    v2 = v2 + eigenvec[0][i-20] / segma1[i]
bottom.append(v2)



print(bottom)



[0.7981624566644688, 0.04853211816300686, 0.03197265259121061, 0.06512529131971002, 0.04307952711147635]


In [106]:
theta_first = []
for i in range(5):
        p_first = eigenvec[0][i]/re[i]**0.5 / bottom[i]
        theta_first.append(p_first)
print('theta for first eigenportfolio',theta_first)

theta for first eigenportfolio [-0.2370942109861452, 21.928409178080322, -1.298081210939348, -0.5341016845613499, -0.012613030684163005]
